\c live023

--ALTER TABLE Customers ADD COLUMN Email VARCHAR(150);
-- ALTER TABLE Customers ALTER COLUMN FirstName SET DATA TYPE VARCHAR(60);
-- ALTER TABLE Customers ADD COLUMN Age INT;
-- ALTER TABLE Customers RENAME COLUMN Age TO Birthdate;
-- ALTER TABLE Customers RENAME COLUMN Birthdate TO Age;
ALTER TABLE Customers ALTER COLUMN Age SET DEFAULT 0;